openapi: 3.0.0
info:
  title: Public API
  version: '1.0'
  description: |-
    Use Koust API to create a custom integration with your system.

    To use Koust API, you'll need to:

      - Use the access token ([see details](https://koust.stoplight.io/docs/koust-api-documentation/reference/Authentication.v1.yaml))

    If you have questions, we're available at [contact@koust.fr](mailto:contact@koust.fr) to help.
servers:
  - url: 'https://api.koustapp.com/apex/rest/public_api'
paths:
  /ingredients:
    parameters: []
    get:
      summary: List ingredients
      operationId: get-ingredients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  content:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - name
                        - unit
                        - price
                        - default_edc_delay
                        - is_food
                        - auto_order
                        - inventory_counting
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                          minLength: 1
                        unit:
                          type: string
                          minLength: 1
                        price:
                          type: string
                          minLength: 1
                        default_edc_delay:
                          type: number
                        is_food:
                          type: boolean
                        category:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                              minLength: 1
                          required:
                            - id
                            - name
                        stock:
                          type: object
                          properties:
                            current:
                              type: number
                            minimum:
                              type: number
                          required:
                            - current
                            - minimum
                        suppliers:
                          type: array
                          uniqueItems: true
                          minItems: 1
                          items:
                            required:
                              - id
                              - name
                              - price
                              - reference
                              - barcode
                              - retained
                              - delivery_min_date
                            properties:
                              id:
                                type: number
                              name:
                                type: string
                                minLength: 1
                              price:
                                type: number
                              reference:
                                type: string
                                minLength: 1
                              allergens:
                                type: array
                                uniqueItems: true
                                minItems: 1
                                items:
                                  required:
                                    - id
                                    - name
                                  properties:
                                    id:
                                      type: string
                                      minLength: 1
                                    name:
                                      type: string
                                      minLength: 1
                              barcode:
                                type: string
                                minLength: 1
                              retained:
                                type: boolean
                              conditioning:
                                type: object
                                properties:
                                  text:
                                    type: string
                                    minLength: 1
                                required:
                                  - text
                              delivery_min_date:
                                type: string
                                minLength: 1
                        auto_order:
                          type: boolean
                        inventory_counting:
                          type: number
                        storage_areas:
                          type: array
                          items:
                            required: []
                            properties: {}
                  page:
                    type: number
                  elements:
                    type: number
                required:
                  - content
                  - page
                  - elements
                x-examples:
                  example-1:
                    content:
                      - id: 236775
                        name: Beurre
                        unit: Kg
                        price: '5'
                        default_edc_delay: 3
                        is_food: true
                        category:
                          id: 120252
                          name: Divers
                        stock:
                          current: -85.80246333333334
                          minimum: 0
                        suppliers:
                          - id: 363
                            name: S METRO
                            price: 2.5
                            quantity_unit: 0.5
                            allergens:
                              - id: L
                                name: Lait
                            retained: true
                            conditioning:
                              text: Carton de
                              value: 12
                            delivery_min_date: '2022-04-11'
                          - id: 2680
                            name: ' Reseau KRILL'
                            price: 5.56
                            reference: 094062 (SAXO)
                            allergens:
                              - id: L
                                name: Lait
                            barcode: '3057640117008'
                            retained: true
                            conditioning:
                              text: Carton de
                            delivery_min_date: '2022-04-09'
                          - id: 167560
                            name: ' Mon Crémier'
                            retained: true
                            delivery_min_date: '2022-04-08'
                        auto_order: true
                        inventory_counting: 0.5
                        storage_areas: []
                    page: 0
                    elements: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - status
                  - message
                x-examples:
                  example-1:
                    status: failure
                    message: Veuillez saisir un nombre de lignes (pagination).
              examples:
                Missing pageNumber parameter:
                  value:
                    status: failure
                    message: Veuillez saisir un numéro de page (pagination).
                Missing numberOfRows parameter:
                  value:
                    status: failure
                    message: Veuillez saisir un nombre de lignes (pagination).
        '401':
          description: Unauthorized
        '555':
          description: 'Error, please, contact us.'
      description: Use this endpoint to retrieve the list of ingredients
      parameters:
        - $ref: ./KoustPOS.v1.yaml#/components/parameters/Authorization
        - schema:
            type: number
          in: query
          name: pageNumber
          description: The page number (starting at 0)
          required: true
        - schema:
            type: number
          in: query
          name: numberOfRows
          description: The number of rows to return
          required: true
        - schema:
            type: string
          in: query
          name: search
          description: Ingredient name searched
  /recipes:
    get:
      summary: List recipes
      tags: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    content:
                      - id: 360
                        name: Banana split
                        category: Dessert
                        portions: 12.1
                        price: 4.2
                        tva: 0.1
                        weight: 100
                        food_cost: 0.161
                        total_cost: 0.161
                        ratio: 23.65
                        order:
                          - id: 16341
                            service: Uber
                            commission: 0.25
                            ratio: 17.79
                          - id: 16344
                            service: Deliveroo
                            commission: 0.31
                            ratio: 16.36
                          - id: 16345
                            service: Just Eat
                            commission: 0.26
                            ratio: 17.55
                        ingredients:
                          - id: 460
                            name: Banane
                            is_food: true
                            unit_price: 9
                            amount: 1
                            unit: unité
                            price: 1.125
                            loss: 0
                          - id: 562
                            name: Vrac vanille
                            is_food: true
                            unit_price: 3
                            amount: 0.12
                            unit: L
                            price: 0.36
                            loss: 0
                          - id: 564
                            name: Vrac chocolat
                            is_food: true
                            unit_price: 2
                            amount: 0.14
                            unit: L
                            price: 0.322
                            loss: 0
                        subrecipes:
                          - id: 31441
                            unit_price: 0.15
                            amount: 1
                            unit: Portion(s)
                            price: 0.1467
                        steps:
                          - position: 1
                            description: Eplucher la banane
                          - position: 2
                            description: Poser la banane au milieu
                        description: ''
                        youtube_url: ''
                        days_validity: 2
                        tags:
                          - name: Origine France
                        nutritional_values:
                          portion: 1
                          kj: 0
                          kcal: 0
                          fat: 0
                          saturated: 0
                          polyunsaturated: 0
                          monounsaturated: 0
                          carbs: 0
                          sugar: 0
                          polyol: 0
                          starch: 0
                          fiber: 0
                        gemrcn:
                          criteria:
                            - name: Crudites
                            - name: Desserts de fruits cru
                          quantities:
                            - type: Maternelle
                              quantity: 20
                            - type: Adulte
                              quantity: 70
                      - id: 360
                        name: Banana split
                        category: Dessert
                        portions: 12.1
                        price: 4.2
                        tva: 0.1
                        weight: 100
                        food_cost: 0.161
                        total_cost: 0.161
                        ratio: 23.65
                        order:
                          - id: 16341
                            service: Uber
                            commission: 0.25
                            ratio: 17.79
                          - id: 16344
                            service: Deliveroo
                            commission: 0.31
                            ratio: 16.36
                          - id: 16345
                            service: Just Eat
                            commission: 0.26
                            ratio: 17.55
                        ingredients:
                          - id: 460
                            name: Banane
                            is_food: true
                            unit_price: 9
                            amount: 1
                            unit: unité
                            price: 1.125
                            loss: 0
                          - id: 562
                            name: Vrac vanille
                            is_food: true
                            unit_price: 3
                            amount: 0.12
                            unit: L
                            price: 0.36
                            loss: 0
                          - id: 564
                            name: Vrac chocolat
                            is_food: true
                            unit_price: 2
                            amount: 0.14
                            unit: L
                            price: 0.322
                            loss: 0
                        subrecipes:
                          - id: 31441
                            unit_price: 0.15
                            amount: 1
                            unit: Portion(s)
                            price: 0.1467
                        steps:
                          - position: 1
                            description: Eplucher la banane
                          - position: 2
                            description: Poser la banane au milieu
                        description: ''
                        youtube_url: ''
                        days_validity: 2
                        tags:
                          - name: Origine France
                        nutritional_values:
                          portion: 1
                          kj: 0
                          kcal: 0
                          fat: 0
                          saturated: 0
                          polyunsaturated: 0
                          monounsaturated: 0
                          carbs: 0
                          sugar: 0
                          polyol: 0
                          starch: 0
                          fiber: 0
                        gemrcn:
                          criteria:
                            - name: Crudites
                            - name: Desserts de fruits cru
                          quantities:
                            - type: Maternelle
                              quantity: 20
                            - type: Adulte
                              quantity: 70
                    page: 0
                    elements: 1
                properties:
                  content:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        category:
                          type: string
                        portions:
                          type: number
                        price:
                          type: number
                        tva:
                          type: number
                        weight:
                          type: number
                        food_cost:
                          type: number
                        total_cost:
                          type: number
                        ratio:
                          type: number
                        order:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: number
                              service:
                                type: string
                              commission:
                                type: number
                              ratio:
                                type: number
                        ingredients:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: number
                              name:
                                type: string
                              is_food:
                                type: boolean
                              unit_price:
                                type: number
                              amount:
                                type: number
                              unit:
                                type: string
                              price:
                                type: number
                              loss:
                                type: number
                        subrecipes:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: number
                              unit_price:
                                type: number
                              amount:
                                type: number
                              unit:
                                type: string
                              price:
                                type: number
                        steps:
                          type: array
                          items:
                            type: object
                            properties:
                              position:
                                type: number
                              description:
                                type: string
                        description:
                          type: string
                        youtube_url:
                          type: string
                        days_validity:
                          type: number
                        tags:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                        nutritional_values:
                          type: object
                          properties:
                            portion:
                              type: number
                            kj:
                              type: number
                            kcal:
                              type: number
                            fat:
                              type: number
                            saturated:
                              type: number
                            polyunsaturated:
                              type: number
                            monounsaturated:
                              type: number
                            carbs:
                              type: number
                            sugar:
                              type: number
                            polyol:
                              type: number
                            starch:
                              type: number
                            fiber:
                              type: number
                        gemrcn:
                          type: object
                          properties:
                            criteria:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                            quantities:
                              type: array
                              items:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  quantity:
                                    type: number
                      required:
                        - id
                        - name
                  page:
                    type: number
                  elements:
                    type: number
                required:
                  - content
                  - page
                  - elements
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                required:
                  - status
                  - message
        '401':
          description: Unauthorized
        '555':
          description: 'Error, please, contact us.'
      operationId: get-recipes
      description: Use this endpoint to retrieve the list of recipes.
      parameters:
        - $ref: ./KoustPOS.v1.yaml#/components/parameters/Authorization
        - schema:
            type: number
          in: query
          name: pageNumber
          description: The page number (starting at 0)
          required: true
        - schema:
            type: number
          in: query
          name: numberOfRows
          description: The number of rows to return
          required: true
        - schema:
            type: string
          in: query
          name: search
          description: Recipe name searched
  /bills:
    post:
      summary: Bills Webhook
      operationId: post-bills
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success_Bills_Model'
              examples:
                Success:
                  value:
                    status: success
                    message: 'Demande d''extraction prise en compte, vos données vont être envoyées à l''url mentionnée.'
                    content:
                      bills_returned: '2'
                      establishment_name: Restau du coin
        '400':
          description: An error occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_Bills_Model'
              examples:
                Error url:
                  value:
                    status: Failed
                    message: Un url de retour doit être mentionnée.
                Error date null:
                  value:
                    status: Failed
                    message: La date de début doit être mentionnée.
                Error format date:
                  value:
                    status: Failed
                    message: La date de fin ne respecte pas le bon format.
                Error start date is more recent:
                  value:
                    status: Failed
                    message: La date de fin doit être supérieur à la date de fin.
                Error content:
                  value:
                    status: Failed
                    message: Veuillez vérifier le contenu de votre requête.
        '401':
          description: Cannot authenticate user
      description: |-
        **Webhook who sends your bills for the chosen dates at the requested url**
        * The Webhook returns the body containing the bills in json format to the URL you requested. You will find the Webhook answer model at the following link : 
          [Weebhook-Model](KoustPublic.v1.yaml/components/schemas/Webhook_Model)
      parameters:
        - $ref: ./Authentication.v1.yaml#/components/parameters/Content-Type
        - $ref: '#/components/parameters/Authorization'
      security:
        - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bills-Model'
            examples:
              Example:
                value:
                  url_callback: string
                  date_interval:
                    start_from: YYYY-MM-DD
                    end_at: YYYY-MM-DD
        description: ''
      x-internal: true
    get:
      summary: List bills
      operationId: get-bills
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    bills:
                      - id: 252374
                        supplier:
                          id: 90384
                          name: A2S
                        invoice_date: '2022-01-11T13:20:49Z'
                        delivery_date: '2022-01-11T00:00:00Z'
                        deadline_date: '2022-02-05T00:00:00Z'
                        invoice_total: 464.504
                        items:
                          - id: 261618
                            name: 1KG CHOCOLAT POUDRE VAN HOUTEN SPE BAR
                            unit: Kg
                            quantity: 1.9
                            price: 7
                            contenance_supplier: 10
                            supplier_retained: 'Y'
                    page_number: 0
                    number_of_elements: 1
                properties:
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        supplier:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                        invoice_date:
                          type: string
                        delivery_date:
                          type: string
                        deadline_date:
                          type: string
                        invoice_total:
                          type: number
                        items:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              unit:
                                type: string
                              quantity:
                                type: number
                              price:
                                type: integer
                              contenance_supplier:
                                type: integer
                              supplier_retained:
                                type: string
                  page:
                    type: integer
                  elements:
                    type: integer
              examples:
                Bill:
                  value:
                    content:
                      - id: 252374
                        supplier:
                          id: 90384
                          name: A2S
                        invoice_date: '2022-01-11T13:20:49Z'
                        delivery_date: '2022-01-11T00:00:00Z'
                        deadline_date: '2022-02-05T00:00:00Z'
                        invoice_total: 14.5
                        items:
                          - id: 261618
                            name: 1KG CHOCOLAT POUDRE VAN HOUTEN SPE BAR
                            unit: Kg
                            quantity: 2
                            price: 7.25
                            contenance_supplier: 1
                            supplier_retained: 'Y'
                    page: 0
                    elements: 1
      description: |
        Use this endpoint to retrieve the list of bills between two dates
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - schema:
            type: string
          in: query
          name: date_from
          description: Starting date
          required: true
        - schema:
            type: string
          in: query
          name: date_to
          description: Ending date
          required: true
        - schema:
            type: string
          in: query
          name: pageNumber
          description: The page number (starting at 0)
          required: true
        - schema:
            type: string
          in: query
          name: numberOfRows
          description: The number of rows to return
          required: true
components:
  schemas:
    Bills-Model:
      title: Bills-Model
      type: object
      properties:
        url_callback:
          type: string
        date_interval:
          type: object
          required:
            - start_from
            - end_at
          properties:
            start_from:
              type: string
            end_at:
              type: string
      required:
        - url_callback
    Error_Bills_Model:
      title: Error_Bills_Model
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    Success_Bills_Model:
      title: Success_Bills_Model
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        content:
          type: object
          properties:
            bills_returned:
              type: string
            establishment_name:
              type: string
    Webhook_Model:
      title: Webhook_Model
      type: array
      items:
        type: object
        properties:
          invoice:
            type: string
          invoice_supplier:
            type: object
            properties:
              supplier_id:
                type: string
              supplier_name:
                type: string
          invoice_date:
            type: string
          delivery_date:
            type: string
          deadline_date:
            type: string
          invoice_total:
            type: string
          invoice_items:
            type: array
            items:
              type: object
              properties:
                ingredient_id:
                  type: string
                ingredient_name:
                  type: string
                ingredient_unit:
                  type: string
                ingredient_quantity:
                  type: string
                ingredient_price:
                  type: string
                ingredient_contenance:
                  type: string
                ingredient_contenance_supplier:
                  type: string
                ingredient_conditioning_value:
                  type: string
                ingredient_supplier_retained:
                  type: string
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        default: application/json
      description: Resource MIME
    Authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
        default: ' Bearer YOUR_ACCESS_TOKEN'
      description: Authorization Header
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://auth.koustapp.com/apex/rest/public_authentication/get_access_token'
          scopes: {}
          refreshUrl: 'https://auth.koustapp.com/apex/rest/public_authentication/refresh_token'
